apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: netflix-cert
spec:
  secretName: netflix-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: netflix.kerocam.com
  dnsNames:
  - netflix.kerocam.com
  - meteo.kerocam.com